version: "3.7"
services:
  web:
    image: node:alpine
    container_name: react-template
    entrypoint: /bin/sh
    build:
      context: ../Dockerfile
      target: $NODE_ENV
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    ports:
      - 3000:3000
    volumes:
     - type: bind
       source: ./
       target: /srv/app
    tty: true
    environment:
      VITE_REACT_APP_API_URL: ${!VITE_REACT_APP_API_URL}
      VITE_REACT_APP_API_KEY: ${!VITE_REACT_APP_API_KEY}
